### ISSUE TITLE
Installation error  installing v0.8.3 - /usr/local/sbin... does not exist

### ISSUE THREAD

**Issue by kloudtaxi** [TheNewNormal/kube-solo-osx#113]
function check_corectld_server() in functions.sh tries to execute the following...
CHECK_SERVER_STATUS=$(/usr/local/sbin/corectld status 2>&1 | grep "Uptime:") 

which returns an error as /usr/local/sbin does not exist. manually creating 'sbin' directory under /usr/local solves the issue.

**Comment by rimusz** [comment]
@kloudstudio can you explain your steps how got the error in more details, so I can reproduce the problem?
thanks

**Comment by rimusz** [comment]
@kloudstudio ok, I see that, thanks
By intention `corectl` files are put to `/usr/local/sbin` so that does not interfere  with `corectl` files installed in other folders.
btw kube apps should only be used with `corectl.app` allow users (not hacky ones) to simplify Apps use.

If you want to use in your way, that's fine too, but I do not see this as the issue, so closing this one.

**Comment by kloudtaxi** [comment]
@rimusz apologies for the delayed response. 

I think I understand the issue now; I agree with you on putting files in `/usr/local/sbin` my point was on OS X `.../local/sbin` was not created after installing `corectl.app`. I had to create it manually. once I did that kube-solo app worked as expected.  

retrospectively I should have opened a bug in `corectl.app` repo.

**Comment by rimusz** [comment]
@kloudstudio I think I know what happened `corectl.app` 
At the start it check that is the first install and opened a new terminal window to save your `sudo` and continued to start all processes but as the `sudo` password was not available yet, so `corectl` files had no chance to be copied to inexistent folder.

Working on that corner case.
