### ISSUE TITLE
Add NFS mount point

### ISSUE THREAD

**Issue by chrislovecnm** [TheNewNormal/kube-solo-osx#55]
Is it possible to add another NFS mount point to the image when it starts?

Thanks

**Comment by rimusz** [comment]
@AntonioMeireles ping

**Comment by AntonioMeireles** [comment]
it is. the issue is how to do that in a simple/reliable way (i.e via some sort of machinery we provide). 
to do it manually one just need to have it available on host and on VMs side pass via custom cloud-config   a specific systems service set to mount it at boot (similar to the one that mounts inside the VM the host's homedir.

**Comment by rimusz** [comment]
@chrislovecnm NFS is disabled, too many issues with it
